version: "3.9"

services:
    app:
        build:
            context: .
            target: sentry
        image: jacoblincool/ntnu-course-sentry
        environment:
            - DEBUG=cli,sentry*
        volumes:
            - ./config.yml:/config.yml
        restart: unless-stopped
